[package]
name = "cudos-cosmwasm-test"
version = "0.0.1"
authors = ["Tugay Emin <tugay.emin@limechain.tech>"]
edition = "2018"
description = "Test helper for cudos-specific contracts that runs a local cudos-node"
repository = "https://github.com/CudoVentures/cudos-cosmwasm-bindings"
license = "Apache-2.0"
readme = "README.md"

[dependencies]
cosmwasm-std = "=1.2.7"
cudos-cosmwasm = { path = "../cudos-cosmwasm", version = "0.0.7" }
serde = { version = "=1.0.103", default-features = false, features = ["derive"] }
serde_json = "=1.0.81"
base64 = "=0.13.0"
thiserror = "1.0.0"
anyhow = "1"