[package]
name = "cudos-cosmwasm"
version = "0.0.7"
authors = ["Lyubomir Yonchev <lyubomir.yonchev@limechain.tech>"]
edition = "2018"
description = "Bindings for CosmWasm contracts to call into custom modules of Cudos Node"
repository = "https://github.com/CudoVentures/cudos-cosmwasm-bindings"
license = "Apache-2.0"
readme = "README.md"

[features]
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = "=1.2.7"
schemars = "=0.8.3"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }

[dev-dependencies]
cosmwasm-schema = "=1.2.7"
